config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :authors, only: [ :index, :show, :create, :update, :destroy, :edit, :new ]
  resources :books, only: [ :index, :show, :create, :update, :destroy, :edit, :new ]
  resources :users, only: [ :index, :show, :create, :update, :destroy, :edit, :new ]
  resources :profiles, only: [ :index, :show, :create, :update, :destroy, :edit, :new ]
  resources :physicians
  resources :patients
  resources :appointments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :physician
  belongs_to :patient

  validates :appointment_date, :location, :status, presence: true
  validates :status, inclusion: { in: %w[Scheduled Completed Cancelled], message: "%{value} is not a valid status" }
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :physicians, through: :appointments
end

app/models/physician.rb
class Physician < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
    @authors = Author.all
  end

  def create
    @book = Book.new(book_params)
  
    if @book.save
      redirect_to @book
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def book_params
      params.require(:book).permit(:title, :content, :author_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @authors = Author.all
    @books = Book.all
    @users = User.all
    @profiles = Profile.all
    @appointments = Appointment.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    @user.build_profile
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def user_params
      params.require(:user).permit(:email, profile_attributes: [:name, :gender, :bio])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Associations" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <%= render 'shared/navbar' %>
  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="bg-gray-800 p-4 fixed top-0 left-0 w-full z-50">
  <div class="container mx-auto flex justify-between items-center">
    <div class="text-white text-lg font-semibold">G</div>
    <div class="space-x-4">
      <%= link_to 'Home', root_path, class: 'text-gray-300 hover:text-white' %>
      <%= link_to 'Authors', authors_path, class: 'text-gray-300 hover:text-white' %>
      <%= link_to 'Books', books_path, class: 'text-gray-300 hover:text-white' %>
      <%= link_to 'Users', users_path, class: 'text-gray-300 hover:text-white' %>
      <%= link_to 'Appointments', appointments_path, class: 'text-gray-300 hover:text-white' %>
      <%= link_to 'Patients', patients_path, class: 'text-gray-300 hover:text-white' %>
      <%= link_to 'Physicians', physicians_path, class: 'text-gray-300 hover:text-white' %>
      <%= link_to 'New Author', new_author_path, class: 'text-gray-300 hover:text-white' %>
      <%= link_to 'New Book', new_book_path, class: 'text-gray-300 hover:text-white' %>
      <%= link_to 'New User', new_user_path, class: 'text-gray-300 hover:text-white' %>
      <%= link_to 'New Appointment', new_appointment_path, class: 'text-gray-300 hover:text-white' %>
      <%= link_to 'New Patient', new_patient_path, class: 'text-gray-300 hover:text-white' %>
      <%= link_to 'New Physician', new_physician_path, class: 'text-gray-300 hover:text-white' %>
    </div>
  </div>
</nav>