config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :authors, only: [ :index, :show, :create, :update, :destroy, :edit, :new ]
  resources :books, only: [ :index, :show, :create, :update, :destroy, :edit, :new ]
  resources :users, only: [ :index, :show, :create, :update, :destroy, :edit, :new ]
  resources :profiles, only: [ :index, :show, :create, :update, :destroy, :edit, :new ]
  resources :physicians
  resources :patients
  resources :appointments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :physician
  belongs_to :patient

  validates :appointment_date, :location, :status, presence: true
  validates :status, inclusion: { in: %w[Scheduled Completed Cancelled], message: "%{value} is not a valid status" }
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :physicians, through: :appointments
end

app/models/physician.rb
class Physician < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to @author
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def author_params
      params.require(:author).permit(:name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
    @authors = Author.all
  end

  def create
    @book = Book.new(book_params)
  
    if @book.save
      redirect_to @book
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def book_params
      params.require(:book).permit(:title, :content, :author_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @authors = Author.all
    @books = Book.all
    @users = User.all
    @profiles = Profile.all
    @appointments = Appointment.all
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.all
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to @patient
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])

    if @patient.update(patient_params)
      redirect_to @patient
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    redirect_to patients_path, status: :see_other
  end

  private
  def patient_params
    params.require(:patient).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    @user.build_profile
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def user_params
      params.require(:user).permit(:email, profile_attributes: [:name, :gender, :bio])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="container p-6 mx-auto">
<h1 class="text-3xl font-bold text-center my-8 pt-20" style="margin-top: -2rem;">Associations Testing</h1>


<div class="container mx-auto mt-8">
  <h2 class="mb-4 text-xl font-semibold text-gray-700">Authors and Books</h2>
  <table class="min-w-full bg-white border rounded-lg shadow-md">
    <thead>
      <tr>
        <th class="px-6 py-4 text-left text-sm font-medium text-gray-500 uppercase border-b">Author</th>
        <th class="px-6 py-4 text-left text-sm font-medium text-gray-500 uppercase border-b">Books</th>
      </tr>
    </thead>
    <tbody>
      <% @authors.each do |author| %>
        <tr>
          <td class="px-6 py-4 border-b text-gray-800 font-semibold"><%= author.name %></td>
          <td class="px-6 py-4 border-b">
            <ul>
              <% author.books.each do |book| %>
                <li>
                  <%= link_to book.title, book_path(book), class: "text-blue-500 hover:underline" %>
                </li>
              <% end %>
            </ul>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="mt-4">
      <%= link_to 'View All Authors', authors_path, class: "text-blue-600 hover:text-blue-800 font-semibold" %>
  </div>
</div><br>

<div class="container mx-auto mt-8">
  <section class="bg-white border rounded-lg shadow-md p-6">
    <h2 class="mb-4 text-xl font-semibold text-gray-700">Users and Profiles</h2>
    <table class="min-w-full">
      <thead>
        <tr>
          <th class="px-6 py-4 text-left text-sm font-medium text-gray-500 uppercase border-b">Email</th>
          <th class="px-6 py-4 text-left text-sm font-medium text-gray-500 uppercase border-b">Profile</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td class="px-6 py-4 border-b text-gray-800 font-semibold"><%= user.email %></td>
              <td class="px-6 py-4 border-b text-gray-800"><%= user.profile ? user.profile.name : "No profile" %></td>
              <td class="px-6 py-4 border-b text-gray-800"><%= user.profile ? user.profile.gender : "No profile" %></td>
              <td class="px-6 py-4 border-b text-gray-800"><%= user.profile ? user.profile.bio : "No profile" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </section>
  <div class="mt-4">
      <%= link_to 'View All Users', users_path, class: "text-blue-600 hover:text-blue-800 font-semibold" %>
  </div>
</div>
<br>
<div class="container mx-auto mt-8">
  <section class="bg-white border rounded-lg shadow-md p-6">
    <h2 class="mb-4 text-xl font-semibold text-gray-700">Appointments</h2>
    <table class="min-w-full">
      <thead>
        <tr>
          <th class="px-6 py-4 text-left text-sm font-medium text-gray-500 uppercase border-b">Appointment ID</th>
          <th class="px-6 py-4 text-left text-sm font-medium text-gray-500 uppercase border-b">Physician</th>
          <th class="px-6 py-4 text-left text-sm font-medium text-gray-500 uppercase border-b">Patient</th>
          <th class="px-6 py-4 text-left text-sm font-medium text-gray-500 uppercase border-b">Date & Time</th>
          <th class="px-6 py-4 text-left text-sm font-medium text-gray-500 uppercase border-b">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% counter = 1 %>
        <% @appointments.each do |appointment| %>
          <tr class="border-b hover:bg-gray-50">
            <td class="px-6 py-4 text-gray-800 font-semibold">
              <%= link_to "#{counter}", appointment_path(appointment), class: "text-blue-500 hover:underline" %>
            </td>
            <td class="px-6 py-4">
              <%= appointment.physician.name if appointment.physician %>
            </td>
            <td class="px-6 py-4">
              <%= appointment.patient.name if appointment.patient %>
            </td>
            <td class="px-6 py-4">
              <%= appointment.appointment_date.strftime("%B %d, %Y %I:%M %p") %>
            </td>
            <td class="px-6 py-4">
              <%= link_to "Edit", edit_appointment_path(appointment), class: "text-blue-500 hover:underline mr-4" %>
              <%= link_to "Delete", appointment, method: :delete, data: { confirm: "Are you sure?" }, class: "text-red-500 hover:underline" %>
            </td>
          </tr>
          <% counter += 1 %>
        <% end %>
      </tbody>
    </table>
  </section>
  <div class="mt-4">
    <%= link_to 'View All Appointments', appointments_path, class: "text-blue-600 hover:text-blue-800 font-semibold" %>
  </div>
  <br>
</div>
</div>